# Generated by Django 4.1.1 on 2023-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0002_bebidas_venda_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
