# Generated by Django 4.1.1 on 2023-10-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0003_venda_preco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='preco',
        ),
    ]
