# Generated by Django 4.1.1 on 2023-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0004_remove_venda_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='bebidas',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
    ]
