# Generated by Django 4.1.1 on 2023-10-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0006_venda_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='total',
        ),
    ]
