# Generated by Django 4.1.1 on 2023-10-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0007_remove_venda_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='nome',
            new_name='nome_bebida',
        ),
    ]
