# Generated by Django 4.1.1 on 2023-10-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0008_rename_nome_venda_nome_bebida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='nome_bebida',
            new_name='id_bebida',
        ),
    ]
