# Generated by Django 4.1.1 on 2023-10-27 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0011_alter_venda_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venda',
            name='hora_venda',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
