# Generated by Django 4.1.1 on 2023-10-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0012_venda_data_venda_venda_hora_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bebidas',
            old_name='preco',
            new_name='preco_unitario',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='preco',
            new_name='preco_unitario',
        ),
    ]
