# Generated by Django 4.1.1 on 2023-10-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0013_rename_preco_bebidas_preco_unitario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='id',
        ),
        migrations.AddField(
            model_name='venda',
            name='id_venda',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
