# Generated by Django 4.2.6 on 2023-10-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0015_remove_venda_id_bebida_alter_bebidas_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='id_bebida',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bebidas.bebidas', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venda',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
