# Generated by Django 4.2.6 on 2023-10-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bebidas', '0018_remove_venda_nome_remove_venda_preco_unitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='id_bebida',
            new_name='produto',
        ),
    ]
